server:
  port: 80
#encoding
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#dbms
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.username=scott
#spring.datasource.password=1234
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none
logging:
  file:
    path: "logback-spring.xml"
  level:
    org:
      thymeleaf: ERROR