server:
  port: 80
#encoding
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#dbms
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.username=scott
#spring.datasource.password=1234
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/free?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: admin123!
    mapper-locations=classpath: /mybatis/**/*.xml

# mybatis
mybatis:
  type-aliases-package: com.spring.final_project
  mapper-locations: static/mybatis/mapper/*.xml
  config-location: classpath:/static/mybatis/config/mybatis-config.xml



logging:
  file:
    path: "logback-spring.xml"
  level:
    org:
      thymeleaf: ERROR




