server:
  port: 80
#encoding
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.192.130.123:3306/free?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: free
    password: Admin123!
    mapper-locations=classpath: /mybatis/**/*.xml

# mybatis
mybatis:
  type-aliases-package: com.spring.final_project
  mapper-locations: static/mybatis/mapper/*.xml
  config-location: classpath:/static/mybatis/config/mybatis-config.xml

logging:
  file:
    path: "logback-spring.xml"
  level:
    org:
      thymeleaf: ERROR


